apiVersion: apps/v1
kind: Deployment
metadata:
  name: l7mp-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: l7mp-operator
  template:
    metadata:
      labels:
        app: l7mp-operator
    spec:
      serviceAccountName: l7mp-account-{{ .Release.Name }}
      containers:
      - name: l7mp-k8s-operator
        image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
